import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import Loader from "../components/loader";

export async function getStaticProps() {
  const res = await fetch("https://www.benjaminmoore.com/api/colors");
  const colors = await res.json();
  return {
    props: {
      colors,
    },
  };
}

export default function Yellow({ colors }) {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    if (colors) {
      setLoading(false);
    }
  }, []);
  if (loading) return <Loader />;
  const [colorName] = Object.entries(colors);
  const colorNames = Object.entries(colorName[1]);
  const yellow = colorNames.filter((color) => color[1].family === "Yellow");
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {yellow &&
            yellow.map((color, index) => {
              const bmColor = color[1];
              return (
                <div
                  className={styles.card}
                  key={index}
                  style={{
                    color: `#${bmColor.hex}`,
                    border: `5px solid #${bmColor.hex}`,
                  }}
                >
                  <p className={styles.bmColorName}>{bmColor.name}</p>
                  <p className={styles.bmColorValue}>{bmColor.family}</p>
                  <p className={styles.bmColorValue}>#{bmColor.hex}</p>
                </div>
              );
            })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
